FROM node:11-alpine as build

WORKDIR /usr/src

# Install packages
COPY package.json package.json
COPY yarn.lock yarn.lock
RUN yarn

COPY . .
RUN yarn build

# production environment
FROM nginx:1.17.6-alpine
COPY --from=build /usr/src/public /usr/share/nginx/html
COPY nginx.conf.d /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
